# Generated by Django 5.0.6 on 2024-06-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('drug', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sequence', models.TextField()),
                ('function', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='overhang',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.CreateModel(
            name='Magic_pool_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('downstream_overhang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_overhang', to='magicpool.overhang')),
                ('upstream_overhang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream_overhang', to='magicpool.overhang')),
            ],
        ),
        migrations.CreateModel(
            name='Magic_pool_part_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('magic_pool_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.magic_pool_part')),
            ],
        ),
        migrations.CreateModel(
            name='Oligo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sequence', models.TextField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.contact')),
            ],
        ),
        migrations.AddField(
            model_name='oligo_info',
            name='oligo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magicpool.oligo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plasmid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('amd_number', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('sequence', models.TextField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.contact')),
                ('vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.feature_type')),
            ],
        ),
        migrations.CreateModel(
            name='Plasmid_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('plasmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.plasmid')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sequence', models.TextField()),
                ('sequence_id', models.CharField(max_length=255)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('strand', models.IntegerField()),
                ('location_str', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('drug_marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.drug_marker')),
                ('feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.feature_type')),
                ('plasmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.plasmid')),
                ('protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.protein')),
            ],
        ),
        migrations.CreateModel(
            name='Protein_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.protein')),
            ],
        ),
        migrations.CreateModel(
            name='Vector_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.magic_pool_part')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('vector_parts', models.ManyToManyField(to='magicpool.vector_part')),
            ],
        ),
    ]
