# Generated by Django 5.0.6 on 2024-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0002_contact_drug_marker_feature_type_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='magic_pool_part_info',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='protein',
            name='function',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('plasmid', 'name')},
        ),
    ]
