# Generated by Django 5.0.6 on 2024-06-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0003_alter_feature_name_alter_magic_pool_part_info_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmid',
            name='drug_markers',
            field=models.ManyToManyField(to='magicpool.drug_marker'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drug_marker',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='magic_pool_part',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='function',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vector',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
