# Generated by Django 5.0.6 on 2024-06-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0004_plasmid_drug_markers_alter_contact_affiliation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='vector_parts',
        ),
        migrations.AddField(
            model_name='vector_part',
            name='vector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magicpool.vector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magicpool.vector'),
        ),
        migrations.AlterUniqueTogether(
            name='vector_part',
            unique_together={('vector', 'order')},
        ),
        migrations.CreateModel(
            name='Vector_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicpool.vector')),
            ],
        ),
    ]
