# Generated by Django 5.0.6 on 2024-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0005_remove_vector_vector_parts_vector_part_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmid',
            name='amd_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
