# Generated by Django 5.0.6 on 2024-06-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0006_alter_plasmid_amd_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='protein',
        ),
        migrations.AddField(
            model_name='protein',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magicpool.feature'),
            preserve_default=False,
        ),
    ]
