# Generated by Django 5.0.6 on 2024-06-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicpool', '0007_remove_feature_protein_protein_feature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set(),
        ),
    ]
